### ISSUE TITLE
Installation Instructions for Linux

### ISSUE THREAD

**Issue by ayushbits** [h0lg/SubTubular#2]
Hi @h0lg ,
I am trying to run your code on Ubuntu system. I've installed Mono-MCS framework but I dont how to proceed further.
Could you help me in running code on Linux based system ?

Additionally, could you provide instructions to compile the project in windows?

**Comment by h0lg** [comment]
Hey @ayushbits ,

I haven't tried **running the executable on Linux**, but theoretically that should work after installing [.NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu) *runtime*.

Concerning **building** - and never mind the OS:
The `SubTubular.csproj` is an [MSBuild](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props) script that you should be able to run via `dotnet build SubTubular.csproj` on any system you can find a .NET Core _SDK_ (containing the [dotnet](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet) command line tool) for.

If you're asking about **developing** or **running the code from source**, you'd want an IDE that supports C# and interfaces with the .NET Core SDK.

I'm currently using [VSCode](https://code.visualstudio.com/) on Windows with the following extensions: 

- [C#](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) language & debugging support
- [NuGet Package Manager](https://marketplace.visualstudio.com/items?itemName=jmrog.vscode-nuget-package-manager) for loading referenced packages
- [.NET Core Tools](https://marketplace.visualstudio.com/items?itemName=formulahendry.dotnet) - Optional. Adds options for running and building the project to the context menu

Good luck!
