### ISSUE TITLE
Can you share a compiled test of v3 for windows?

### ISSUE THREAD

**Issue by 03stevensmi** [h0lg/SubTubular#4]
Hey, I've been following all your work on subtublar since the beggining and is
Used all the time because its a heaven for my research!

Will it be ok if I could get a hold of a compiled Windows build of v3
to test out?

If its going to be released publicly in around this week or next, then don't bother,
I will wait for the official release. ;)

Once again,
Thank you for all the hard and important work you have done on creating this
amazing project!

Cheers,
03stevensmi

**Comment by h0lg** [comment]
Hey @03stevensmi, sorry for the delay. There were some pretty severe issues with my development version that I had to figure out and that kept me from releasing earlier. Happy to hear you find it useful! Check out https://github.com/h0lg/SubTubular/releases/tag/v3.0.0
