### ISSUE TITLE
How do I use this project?

### ISSUE THREAD

**Issue by Devin2019chs** [h0lg/SubTubular#5]
Hello,

I am trying to use this project on my Macbook M1 2020 and I am having such a hard time trying to figure out how to work it. I installed .Net Core 3.1. I downloaded the SubTubular Zip and unzipped it. I go to my Mac Terminal and I first put in "sudo ln -s /usr/local/share/dotnet/x64/dotnet /usr/local/bin/". Then it has me put in my password. After I put my password in this comes up: "ln: /usr/local/bin//dotnet: File exists".  On the next line I put in dotnet and the following shows up:

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

I'm stuck at the path-to-application step. I don't understand what "The path to an application .dll file to execute" means. What am I supposed to put here?

I've tried a few things but this message shows up:

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-file:///Users/devinwalker/Downloads/SubTubular%202.2.2/CommandLine.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

I also tried using this for this specific step: "dotnet build SubTubular.csproj"

When I do this shows up: 

MSBuild version 17.4.0+18d5aef85 for .NET
MSBUILD : error MSB1009: Project file does not exist.
Switch: SubTubular.csproj
devinwalker@Devins-Air ~ % 

When I try to use it it doesn't work.

I've spent all day trying to figure all of this out. I wonder am I doing the steps properly? I would just like to use this for YouTube.

If you can let me know what I am doing wrong I would really appreciate it.

Thank you

**Comment by h0lg** [comment]
Hey @Devin2019chs , sorry for the delay.

I'm not sure if I understand what exactly you're trying to do.
1) compile the app from source or
2) run the binaries included in the release

You running the `dotnet` command suggest 1) to me, but `Project file does not exist.` suggests that you're doing that either in the wrong folder on trying to run the `dotnet` command on the already compiled binaries, which you don't have to do.

To 2) run the binaries, just navigate your Terminal to the folder you unzipped SubTubular into and then call it from the Terminal as you see in the [Bash examples of the current Readme.md](https://github.com/h0lg/SubTubular#bash-) .

Hope that helps!

**Comment by h0lg** [comment]
The current release updates the project to Visual Studio. So get that on your platform of choice and it'll spin up MsBuild for you.
