### ISSUE TITLE
outputting the URLS only to a text file

### ISSUE THREAD

**Issue by 111100001** [h0lg/SubTubular#7]
is there a way to put the result urls in a text file (only the urls)

**Comment by h0lg** [comment]
No, that's not possible out of the box. But you could output a text file and use Regular expressions to extract the URLs with something like
bash:
```bash
grep -oP 'http[s]?://\S+' yourfile.txt
```

Powershell:
```Powershell
Get-Content yourfile.txt | Select-String -Pattern 'http[s]?://\S+' -AllMatches | ForEach-Object { $_.Matches.Value }
```

**Comment by 111100001** [comment]
thanks!
